name: Panagiotis TSAVDARIS
description: This is Panos' blog
#name: Test Test
#description: This is a test
author: Panagiotis TSAVDARIS
author_email: ptsavdar@gmail.com
url: http://ptsavdar.github.io

category_dir: /

permalink: pretty

markdown: redcarpet

paginate: 5

exclude: [ README.md, Gemfile ]
