# Permalinks
permalink:           pretty

# Setup
title:               Panagiotis Tsavdaris
tagline:             Here lie my journal, thoughts, experience...
url:                 http://ptsavdar.github.io
paginate:            5
baseurl:             ""
category_dir: /

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

exclude: [ README.md, Gemfile, Gemfile.lock ]

# About/contact
author:
  name:              Panagiotis Tsavdaris
  url:               http://ptsavdar.github.io
  email:             ptsavdar@gmail.com

# Includes an icon in the footer for each username you enter
footer-links:
    email: ptsavdar@gmail.com
    facebook: ptsavdar  
    github: ptsavdar
    linkedin: ptsavdar
    twitter: ptsavdar
    stackoverflow: users/3016484/ptsavdar

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/ptsavdar/ptsavdar.github.io

# plugins
plugins:
  - jekyll-paginate
  - jekyll-gist