name: Panagiotis TSAVDARIS
description: This is Panos' blog
#name: Test Test
#description: This is a test
author: Panagiotis TSAVDARIS
author_email: ptsavdar@gmail.com
url: http://ptsavdar.github.io

category_dir: /

permalink: pretty

markdown: redcarpet

paginate: 5

sass:
    sass_dir: _scss
    style: :compressed

exclude: [ README.md, Gemfile, Gemfile.lock ]

# Includes an icon in the footer for each username you enter
footer-links:
    email: ptsavdar@gmail.com
    facebook: ptsavdar  
    github: barryclark/jekyll-now
    linkedin: ptsavdar
    twitter: ptsavdar
    stackoverflow: users/3016484/ptsavdar
